import Foundation

public struct ClipboardItem: Codable, Identifiable, Equatable {
    public var id: UUID
    public var date: Date
    public var pinned: Bool
    public var preview: String
    public var kind: String
    public var digest: String
    public var byteCount: Int
    public init(id: UUID = UUID(), date: Date = Date(), pinned: Bool = false, preview: String, kind: String, digest: String, byteCount: Int) {
        self.id = id; self.date = date; self.pinned = pinned; self.preview = preview
        self.kind = kind; self.digest = digest; self.byteCount = byteCount
    }
}

public enum ClipboardPrivacyFilter {
    public static let defaultExclusions = ["com.agilebits.onepassword7", "com.1password.1password", "com.bitwarden.desktop", "org.keepassxc.keepassxc", "com.apple.Passwords", "com.dashlane.Dashlane", "com.lastpass.LastPass"]
    public static let sensitiveTypes: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType"]
    public static func allows(types: Set<String>, source: String?, exclusions: Set<String>) -> Bool {
        guard types.isDisjoint(with: sensitiveTypes) else { return false }
        return source.map { !exclusions.contains($0) } ?? true
    }
}

public enum HistoryPolicy {
    /// Pins survive count trimming but never bypass age/size or the absolute count limit.
    public static func retained(_ items: [ClipboardItem], limit: Int, maxAgeDays: Int, maxBytes: Int, totalByteBudget: Int = .max, now: Date = Date()) -> [ClipboardItem] {
        let cutoff = now.addingTimeInterval(-Double(max(1, maxAgeDays)) * 86400)
        let candidates = items.filter { $0.date >= cutoff && $0.byteCount <= maxBytes && $0.byteCount >= 0 }
            .sorted { $0.pinned != $1.pinned ? $0.pinned : $0.date > $1.date }
        var result: [ClipboardItem] = []
        var available = max(0, totalByteBudget)
        for item in candidates where result.count < max(1, limit) {
            guard item.byteCount <= available else { continue }
            result.append(item); available -= item.byteCount
        }
        return result
    }
}

public struct Shortcut: Codable, Equatable {
    public var keyCode: UInt16
    public var modifiers: UInt64
    public var label: String
    public init(keyCode: UInt16, modifiers: UInt64, label: String) {
        self.keyCode = keyCode; self.modifiers = modifiers; self.label = label
    }
    public func matches(_ other: Shortcut) -> Bool { keyCode == other.keyCode && modifiers == other.modifiers }
}
